# -*- coding: utf-8 -*-
"""Task 1_OASIS

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WPFcStrkUBu5SQgHd3kxaeAtZCuvIJ8F
"""

#importing the needed libraies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.simplefilter("ignore")

#Creating the seperate names for the classification of the iris on the basis of length and width of the sepal and petal
#columns = [ 'Sepal_Length', 'Sepal_Width', 'Petal_Leangth', 'Petal_Width', 'Class_Name']

#importing the dataset 
#df = pd.read_csv('/content/drive/MyDrive/Iris.csv', names = columns)
df = pd.read_csv('/content/drive/MyDrive/Iris.csv')
df.head()

#Checking for the null values
df.isnull().sum()

#Column names
df.columns

# Statistical Analysis of the dataset
df.describe()

#Droping unwanted columns
df = df.drop(columns = "Id")

df

#Vitualizations
df['Species'].value_counts()

sns.countplot(df['Species'])

x = df.iloc[:,:4]
y = df.iloc[:,4]

x

y

#Spliting the data into train and test dataset
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=0)

x_train.shape

y_train.shape

x_test.shape

y_test.shape

#Creating the classification model
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()

model.fit(x_train,y_train)

y_pred = model.predict(x_test)
y_pred

#Accuracy and Confusion matrix
from sklearn.metrics import accuracy_score,confusion_matrix

confusion_matrix(y_test,y_pred)

accuracy=accuracy_score(y_test,y_pred)*100
print("Accuracy of the model is {:.2f}".format(accuracy))